language: python
sudo: required
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.8-dev"

matrix:
  fast_finish: true

jobs:
  include:
  - stage: format-check
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - black --check --diff .

# command to install dependencies
install:
  - pip install -U pip pytest
  - pip install --no-deps -r travis-requirements.txt
# command to run tests
script:
  - ./run_tests.sh all
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
